package praxis

import (
	"bytes"
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

// MarshalYAML flattens a filter entry into a single mapping.
//
// Praxis filter entries carry the structural keys (`filter`, `name`,
// `conditions`, `response_conditions`, `failure_mode`, `branch_chains`)
// alongside the filter's own typed fields at the SAME level — upstream this is
// `#[serde(flatten)]` into a serde_yaml::Value, which is then stripped of the
// structural keys and deserialized into the filter's typed struct with
// unknown-field rejection. Emitting the typed fields under a nested `config:`
// key would therefore be rejected as an unknown field by every builtin filter.
//
// Comments are attached as a head comment on the `filter` key so they render
// immediately above the entry.
func (f Filter) MarshalYAML() (any, error) {
	node := &yaml.Node{Kind: yaml.MappingNode}

	filterKey := &yaml.Node{Kind: yaml.ScalarNode, Value: "filter"}
	if len(f.Comments) > 0 {
		// Wrap each comment so long explanatory notes stay readable in the
		// emitted file instead of running off to a single very long line.
		var lines []string
		for _, c := range f.Comments {
			lines = append(lines, wrapComment(c, 72)...)
		}
		filterKey.HeadComment = strings.Join(lines, "\n")
	}
	filterVal := &yaml.Node{Kind: yaml.ScalarNode, Value: f.Type}
	node.Content = append(node.Content, filterKey, filterVal)

	for _, field := range f.Fields {
		valNode := &yaml.Node{}
		if err := valNode.Encode(field.Value); err != nil {
			return nil, fmt.Errorf("praxis: encoding filter %q field %q: %w", f.Type, field.Key, err)
		}
		node.Content = append(node.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: field.Key},
			valNode,
		)
	}
	return node, nil
}

// header is the comment block prepended to every generated document. It names
// the generator and states the one thing a reader most needs to know: which
// AuthBridge behavior did and did not survive the translation.
const header = `# Praxis proxy configuration — GENERATED from an AuthBridge config.
#
# Generated by authbridge/authlib/praxis (Convert). Edits are overwritten on
# the next run; change the AuthBridge config instead.
#
# Run with:
#   cargo run -p praxis-proxy -- -c %s
# Validate without binding ports:
#   cargo run -p praxis-proxy -- -t -c %s
#
# SCOPE OF THE TRANSLATION
# Structural configuration — listener addresses, the application backend,
# routing, mTLS posture, and the admin/metrics endpoint — is translated
# faithfully. AuthBridge's plugin *enforcement* largely is not: a
# default-feature Praxis build (features = []) compiles in no JWT-validation
# and no RFC 8693 token-exchange filter. Praxis's ` + "`policy`" + ` filter covers
# that ground but requires the off-by-default ` + "`policy-engine`" + ` cargo feature
# plus a separate policy document, and a default build rejects it outright
# ("unknown filter type: 'policy'").
#
# Any AuthBridge plugin without a counterpart is marked UNMAPPED in a comment
# at the position it occupied in the pipeline. Those markers are inert: they
# record the gap, they do not enforce the plugin. Read them before putting this
# in front of anything that was relying on AuthBridge to say no.
`

// Render marshals a Praxis config to YAML with the explanatory header.
//
// configPath is used only to make the header's example commands
// copy-pasteable; it does not have to exist yet.
func Render(cfg *Config, configPath string) ([]byte, error) {
	if cfg == nil {
		return nil, fmt.Errorf("praxis: nil config")
	}
	return renderYAML(fmt.Sprintf(header, configPath, configPath), cfg)
}

// renderYAML writes a comment header followed by v marshalled as YAML. Shared
// by the proxy config and the policy document so both documents use the same
// indentation and header convention.
func renderYAML(header string, v any) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(header)
	buf.WriteString("\n")

	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(v); err != nil {
		return nil, fmt.Errorf("praxis: encoding YAML: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("praxis: closing encoder: %w", err)
	}
	return buf.Bytes(), nil
}

// RenderResult marshals a conversion result, appending the unmapped-plugin
// account and structural warnings as a trailing comment block so the
// generated file carries its own caveats.
func RenderResult(res *Result, configPath string) ([]byte, error) {
	if res == nil {
		return nil, fmt.Errorf("praxis: nil result")
	}
	out, err := Render(res.Config, configPath)
	if err != nil {
		return nil, err
	}
	if len(res.Unmapped) == 0 && len(res.Warnings) == 0 {
		return out, nil
	}

	var buf bytes.Buffer
	buf.Write(out)
	buf.WriteString("\n")
	if len(res.Unmapped) > 0 {
		buf.WriteString("# ── UNMAPPED AUTHBRIDGE PLUGINS ")
		buf.WriteString(strings.Repeat("─", 44))
		buf.WriteString("\n#\n")
		buf.WriteString("# These plugins were NOT translated. The proxy below does not enforce them.\n#\n")
		for _, u := range res.Unmapped {
			writeCommentBlock(&buf, u)
		}
	}
	if len(res.Warnings) > 0 {
		buf.WriteString("#\n# ── STRUCTURAL NOTES ")
		buf.WriteString(strings.Repeat("─", 50))
		buf.WriteString("\n#\n")
		for _, w := range res.Warnings {
			writeCommentBlock(&buf, w)
		}
	}
	return buf.Bytes(), nil
}

// wrapComment splits s into lines of at most width runes, breaking on word
// boundaries. A word longer than width is left on its own line rather than
// being split mid-token, so paths and URLs stay copy-pasteable.
func wrapComment(s string, width int) []string {
	words := strings.Fields(s)
	if len(words) == 0 {
		return nil
	}
	var (
		lines []string
		cur   strings.Builder
	)
	for _, w := range words {
		if cur.Len() > 0 && cur.Len()+1+len(w) > width {
			lines = append(lines, cur.String())
			cur.Reset()
		}
		if cur.Len() > 0 {
			cur.WriteByte(' ')
		}
		cur.WriteString(w)
	}
	if cur.Len() > 0 {
		lines = append(lines, cur.String())
	}
	return lines
}

// writeCommentBlock emits one bullet as wrapped YAML comment lines, with
// continuation lines indented under the bullet.
func writeCommentBlock(buf *bytes.Buffer, s string) {
	lines := wrapComment(s, 68)
	for i, l := range lines {
		if i == 0 {
			buf.WriteString("#   - ")
		} else {
			buf.WriteString("#     ")
		}
		buf.WriteString(l)
		buf.WriteString("\n")
	}
}
