#!/usr/bin/env python3
"""
Output Generators - Policy Output File Generation Utilities

This module provides utilities for generating output files from policy structures,
including YAML and Rego format generation.

Functions:
    - generate_yaml_output: Generate YAML policy file content
    - generate_realm_roles_rego: Generate Rego content for user-to-realm-roles mapping
    - generate_privileges_rego: Generate Rego content for privileges mapping
    - generate_default_rego: Generate Rego content for deny-by-default behavior
    - generate_policy_rego: Generate Rego content for access control policy
"""

from typing import Dict, Optional
import yaml


def generate_yaml_output(policy_structure: dict, description: str = "") -> str:
    """
    Generate YAML output from a policy structure.
    
    Args:
        policy_structure: Dictionary containing the policy structure
        description: Original policy description for comments
        
    Returns:
        Complete YAML policy file content with comments
    """
    # Create header comments
    header = """# Access Control Policy
# Maps user roles (realm roles) to specific privileges
# Format: user_role_name -> list of privilege mappings
# Each entry specifies: service (service name) and privilege (privilege name from that service)

"""
    
    # Add original policy description as comment
    if description:
        description_lines = description.strip().split('\n')
        header += "# Original Policy Description:\n"
        for line in description_lines:
            header += f"#   {line.strip()}\n"
        header += "#\n"
    
    # Generate YAML from policy structure
    yaml_content = yaml.dump(
        policy_structure,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True
    )
    
    # Add footer
    footer = "\n# Generated by PolicyBuilder using LangGraph\n"
    
    # Combine all parts
    return header + yaml_content + footer


def generate_realm_roles_rego(user_to_roles: dict) -> str:
    """
    Generate Rego content for user-to-realm-roles mapping.
    
    Args:
        user_to_roles: Dictionary mapping usernames to lists of realm role names
        
    Returns:
        Rego file content as string
    """
    rego_content = """package authz.realm_roles

# Realm Roles Mapping
# Maps user names to lists of realm role names

realm_roles := {
"""
    
    # Build the dictionary entries
    user_entries = []
    for username in sorted(user_to_roles):
        username_escaped = username.replace('"', '\\"')
        roles = user_to_roles.get(username, [])
        role_list = []
        for role_name in roles:
            role_name_escaped = role_name.replace('"', '\\"')
            role_list.append(f'"{role_name_escaped}"')
        roles_str = ", ".join(role_list)
        user_entries.append(f'    "{username_escaped}": [{roles_str}]')
    
    # Join all entries with commas
    rego_content += ",\n".join(user_entries)
    rego_content += "\n}\n"
    
    return rego_content


def generate_privileges_rego(privileges_map: Dict[str, list], scopes: list) -> str:
    """
    Generate Rego content for privileges mapping by service/client.
    
    Args:
        privileges_map: Dictionary mapping service/client IDs to their privilege lists
                       Each privilege is a dict with 'name' and 'description'
        scopes: List of Scope objects with 'name' and 'description'
        
    Returns:
        Rego file content as string
    """
    rego_content = """package authz.privileges

# Service Privileges Mapping
# Maps service/client IDs to their available privileges

"""
    
    # Create a list of scope names for inclusion in privileges
    scope_names = [scope.name for scope in scopes]
    
    for service_id, privileges in privileges_map.items():
        rego_content += f'service["{service_id}"] := [\n'
        for priv in privileges:
            priv_name = priv.get("name", "")
            priv_desc = priv.get("description", "")
            # Escape quotes in description
            priv_desc = priv_desc.replace('"', '\\"')
            
            rego_content += f'    {{\n'
            rego_content += f'        "name": "{priv_name}",\n'
            rego_content += f'        "description": "{priv_desc}",\n'
            rego_content += f'        "scopes": [\n'
            # Add all available scopes to each privilege
            for scope_name in scope_names:
                scope_name_escaped = scope_name.replace('"', '\\"')
                rego_content += f'            "{scope_name_escaped}",\n'
            rego_content += '        ]\n'
            rego_content += f'    }},\n'
        rego_content += "]\n\n"
    
    return rego_content


def generate_default_rego() -> str:
    """
    Generate Rego content for deny-by-default behavior.
    
    Returns:
        Rego file content as string
    """
    return """package authbridge.outbound.request

default allow := false
"""


def generate_policy_rego(
    policy_structure: dict,
    description: str = "",
    service_filter: Optional[str] = None
) -> str:
    """
    Generate Rego content for the access control policy.
    
    Converts the policy structure (role -> privileges) into Rego allow rules.
    Each rule checks if the user has the required role and matches the service/privilege.
    
    Args:
        policy_structure: Dictionary with 'policy' key containing role-to-privileges mapping
        description: Original policy description for comments
        service_filter: If provided, only generate rules for this specific service
        
    Returns:
        Rego file content as string
    """
    rego_content = """package authbridge.outbound.request

import data.authz.realm_roles.realm_roles

# Access Control Policy
# Uses user -> realm roles mapping to authorize privileges
# Policy entries map realm role names to privilege mappings
# Each entry specifies: service (service name) and privilege (privilege name from that service)

"""
    
    # Add service filter info if applicable
    if service_filter:
        rego_content += f"# Service: {service_filter}\n"
    
    # Add original policy description as comment
    if description:
        description_lines = description.strip().split('\n')
        rego_content += "# Original Policy Description:\n"
        for line in description_lines:
            rego_content += f"#   {line.strip()}\n"
        rego_content += "#\n\n"
    
    # Extract policy from structure
    policy = policy_structure.get("policy", {})
    
    # Generate allow rules for each role and their privileges
    for role_name, privileges in policy.items():
        for priv in privileges:
            service = priv.get("service", "")
            privilege = priv.get("privilege", "")
            service_type = priv.get("service_type")
            
            # Determine protocol based on service type
            # "msp" for Tool type, "a2a" for Agent type
            if service_type == "Tool":
                protocol = "mcp"
            else:
                protocol = "a2a"

            # Skip if service_filter is set and this privilege is for a different service
            if service_filter and service != service_filter:
                continue
            
            # Escape quotes in service and privilege names
            service_escaped = service.replace('"', '\\"')
            privilege_escaped = privilege.replace('"', '\\"')
            
            role_name_escaped = role_name.replace('"', '\\"')
            
            rego_content += f'allow if {{\n'
            rego_content += f'  "{role_name_escaped}" in object.get(realm_roles, input.identity.subject, [])\n'
            rego_content += f'  input.{protocol}.client_id == "{service_escaped}"\n'
            rego_content += f'  "{privilege_escaped}" in input.identity.scopes\n'
            rego_content += "}\n\n"
   
    return rego_content

# Made with Bob
