name: Spellcheck Action
on:
  pull_request:
    branches:
      - main
      - "release-*"
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  spellcheck:
    # disable spell check with 'false' value.
    if: false
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Check spelling
        uses: rojopolis/spellcheck-github-actions@c1934c57e61c734261d7905b525486b12f8eb670  # 0.66.0
        with:
          config_path: .github/spellcheck/.spellcheck.yml
          task_name: Markdown
